baseURL = "https://lillian-lam.github.io/"
languageCode = "en-us"
title = "Your Name"

[params]
  name = "Lillian Lam"
  tagline = "BME & AMS | Graduate Researcher @ JHU"
  photo = "/images/profile_picture.png"

[[params.socials]]
  name = "GitHub"
  url = "https://github.com/Lillian-Lam"

[[params.socials]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/lillian-ngating-lam/"


[[params.socials]]
  name = "Email"
  url = "lillianngatinglam@gmail.com"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4

[markup.goldmark.renderer]
  unsafe = true
